### ISSUE TITLE
PostgreSQL 15 - Ошибка при выполнении CREATE EXTENSION

### ISSUE THREAD

**Issue by xinferum** [postgrespro/pg_tsparser#7]
Добрый день.

Сегодня начал тестировать установку PostgreSQL 15 и столкнулся с такой проблемой - при попытке выполнения "CREATE EXTENSION pg_tsparser;" возникает ошибка:
```
ERROR:  could not load library "/usr/pgsql-15/lib/pg_tsparser.so": /usr/pgsql-15/lib/pg_tsparser.so: undefined symbol: pg_atoi
```

Само расширение собрано из исходников без ошибок на этапе сборки. Файл pg_tsparser.so присутствует.

**Comment by xinferum** [comment]
Судя по поиску в исходниках PostgreSQL, функция pg_atoi удалена из кода PostgreSQL 15, в 14-й версии присутствует.

**Comment by sgrinko** [comment]
Это расширение очень нужно для работы с FTS, так как реализует разбор лексем способом подходящим для поиска сложносоставных слов. Очень ждем исправления для совместимости с 15-й версией Postgres.

**Comment by MarinaPolyakova** [comment]
Вроде как основная ветка модуля - stable, и там это уже починили, см. https://github.com/postgrespro/pg_tsparser/pull/6.

**Comment by xinferum** [comment]
Спасибо, завтра попробую собрать из stable ветки.

**Comment by xinferum** [comment]
Да, из stable собирается успешно и работает.

Подскажите, а когда планируется слияние в мастер и выпуск релиза версии с поддержкой 15-го PostgreSQL этим исправлением?

**Comment by kovdb75** [comment]
Здравствуйте!

>Подскажите, а когда планируется слияние в мастер и выпуск релиза версии с поддержкой
>15-го PostgreSQL этим исправлением?

Отдельного релиза не планируется, для v15 используется ветка stable в её нынешнем состоянии.
Чтобы избежать путаницы, на ветку master выложены исправления с ветки stable, т.е. ветки master и stable сейчас эквивалентны.

**Comment by xinferum** [comment]
Спасибо.
Issue закрываю.

**Comment by MarinaPolyakova** [comment]
> Отдельного релиза не планируется, для v15 используется ветка stable в её нынешнем состоянии.
> Чтобы избежать путаницы, на ветку master выложены исправления с ветки stable, т.е. ветки master и stable сейчас эквивалентны.

Обсудили, что теперь основная ветка модуля - master. Т.е. теперь туда будут попадать нужные изменения по мере их готовности.

**Comment by sgrinko** [comment]
Спасибо!
